(combined as table) as table =>
    let
        ObjectKeys = Table.Buffer(
            Table.AddIndexColumn(
                Table.Distinct(Table.SelectColumns(combined, {"model_id", "object_id"})),
                "object_index",
                0,
                1,
                Int64.Type
            )
        ),

        WithObjectIndex = Table.ExpandTableColumn(
            Table.NestedJoin(combined, {"model_id", "object_id"}, ObjectKeys, {"model_id", "object_id"}, "_o", JoinKind.Inner),
            "_o",
            {"object_index"},
            {"object_index"}
        ),

        WithoutModelId = Table.RemoveColumns(WithObjectIndex, {"model_id"}),

        Renamed = Table.RenameColumns(WithoutModelId, {{"object_id", "Object IDs"}}),

        Typed = Table.TransformColumnTypes(
            Renamed,
            {
                {"object_index", Int64.Type},
                {"Object IDs", type text},
                {"path", type text}
            }
        )
    in
        Typed
