(baseUrl as text, projectId as text, modelId as text, versionId as text, token as text) as table =>
    let
        Extension.LoadFunction = (fileName as text) =>
            let
                binary = Extension.Contents(fileName),
                asText = Text.FromBinary(binary)
            in
                try
                    Expression.Evaluate(asText, #shared)
                catch (e) =>
                    error [
                        Reason = "Extension.LoadFunction Failure",
                        Message.Format = "Loading '#{0}' failed - '#{1}': '#{2}'",
                        Message.Parameters = {fileName, e[Reason], e[Message]},
                        Detail = [File = fileName, Error = e]
                    ],

        FetchEavParquet = Extension.LoadFunction("FetchEavParquet.pqm"),

        Raw = FetchEavParquet(baseUrl, projectId, modelId, versionId, token),

        WithModel = Table.AddColumn(Raw, "model_id", each modelId, type text),

        WithValue = Table.AddColumn(
            WithModel,
            "value",
            each if [value_num] <> null then [value_num] else [value_text]
        ),

        Selected = Table.SelectColumns(
            WithValue,
            {"model_id", "object_id", "path", "value"},
            MissingField.UseNull
        )
    in
        Selected
