// Builds the object/property table from a 4.0 artifact bundle's eav parquet files.
//
// Default (expand = false) — TALL: one row per (object, property):
//   "Application ID" | "Object Type" | "Property" | "Value"
//   Property paths and values come from eav.eav plus type-level parameters
//   (instance values win on the same path); objects with zero properties keep
//   a single row with null Property/Value. This shape drives cross-filtering:
//   slice by Property/Value elsewhere -> the 3D visual receives the matching
//   Application IDs.
//
// expand = true — WIDE: one row per object, one column per property path.
//
//   "Application ID"  — the stable object identity (viewer 2.0 keys objects by this)
//   "Object Type"     — a friendly type label: "Family Name: Type Name" when the
//                       type tables carry them (Revit), else the raw type_key;
//                       null when the optional type tables are absent
//
// deps carries the shared module functions so this file doesn't re-load them:
//   deps[ReadBundleTable](files, suffix, required)
(deps as record, files as list, expand as logical) as table =>
    let
        ReadBundleTable = deps[ReadBundleTable],

        // ---- mandatory tables ----------------------------------------------
        objects = Table.Buffer(
            Table.SelectColumns(
                ReadBundleTable(files, ".eav.objects.parquet", true),
                {"object_index", "application_id"}
            )
        ),
        paths = Table.Buffer(ReadBundleTable(files, ".eav.paths.parquet", true)),
        eav = ReadBundleTable(files, ".eav.eav.parquet", true),

        // ---- optional type tables (graceful skip when absent) --------------
        objectTypeRaw = ReadBundleTable(files, ".eav.object_type.parquet", false),
        objectType = if objectTypeRaw = null then null else Table.Buffer(objectTypeRaw),
        types = ReadBundleTable(files, ".eav.types.parquet", false),
        typeEavRaw = ReadBundleTable(files, ".eav.type_eav.parquet", false),
        typeEav = if typeEavRaw = null then null else Table.Buffer(typeEavRaw),
        hasTypes = objectType <> null and types <> null,

        // one row per type_index with the value of the first type_eav property
        // whose path ends with the given suffix (e.g. ".Type Name")
        TypePropBySuffix = (suffix as text, columnName as text) as table =>
            let
                matchingPaths = Table.SelectRows(paths, each Text.EndsWith([path], suffix)),
                joined = Table.SelectColumns(
                    Table.ExpandTableColumn(
                        Table.NestedJoin(
                            typeEav, {"path_index"},
                            matchingPaths, {"path_index"},
                            "_p", JoinKind.Inner
                        ),
                        "_p", {"path"}, {"__path"}
                    ),
                    {"type_index", "value_string"}
                ),
                distinct = Table.Distinct(joined, {"type_index"})
            in
                Table.RenameColumns(distinct, {{"value_string", columnName}}),

        // type_index -> display label ("Family: Type Name" > type name > type_key)
        typeDisplay = if not hasTypes then
            null
        else if typeEav = null then
            Table.RenameColumns(Table.Buffer(types), {{"type_key", "__typeDisplay"}})
        else
            let
                withName = Table.ExpandTableColumn(
                    Table.NestedJoin(
                        Table.Buffer(types), {"type_index"},
                        TypePropBySuffix(".Type Name", "__typeName"), {"type_index"},
                        "_n", JoinKind.LeftOuter
                    ),
                    "_n", {"__typeName"}, {"__typeName"}
                ),
                withFamily = Table.ExpandTableColumn(
                    Table.NestedJoin(
                        withName, {"type_index"},
                        TypePropBySuffix(".Family Name", "__familyName"), {"type_index"},
                        "_f", JoinKind.LeftOuter
                    ),
                    "_f", {"__familyName"}, {"__familyName"}
                ),
                withDisplay = Table.AddColumn(
                    withFamily,
                    "__typeDisplay",
                    each
                        if [__familyName] <> null and [__typeName] <> null then
                            [__familyName] & ": " & [__typeName]
                        else if [__typeName] <> null then [__typeName]
                        else if [__familyName] <> null then [__familyName]
                        else [type_key],
                    type text
                )
            in
                Table.Buffer(Table.SelectColumns(withDisplay, {"type_index", "__typeDisplay"})),

        typeDisplayPerObject = if typeDisplay <> null then
            Table.SelectColumns(
                Table.ExpandTableColumn(
                    Table.NestedJoin(
                        objectType, {"type_index"},
                        typeDisplay, {"type_index"},
                        "_t", JoinKind.Inner
                    ),
                    "_t", {"__typeDisplay"}, {"__typeDisplay"}
                ),
                {"object_index", "__typeDisplay"}
            )
        else
            null,

        base = if typeDisplayPerObject <> null then
            Table.ExpandTableColumn(
                Table.NestedJoin(
                    objects, {"object_index"},
                    typeDisplayPerObject, {"object_index"},
                    "_tk", JoinKind.LeftOuter
                ),
                "_tk", {"__typeDisplay"}, {"Object Type"}
            )
        else
            Table.AddColumn(objects, "Object Type", each null, type nullable text),

        // ---- tall property pipeline (both modes) ----------------------------
        propCols = {"object_index", "path_index", "value_string", "value_double", "value_boolean"},
        instanceProps = Table.Buffer(Table.SelectColumns(eav, propCols)),

        // type-level params projected per object; instance values win:
        // anti-join drops any (object, path) already present on the instance
        typeProps = if hasTypes and typeEav <> null then
            Table.RemoveColumns(
                Table.NestedJoin(
                    Table.SelectColumns(
                        Table.ExpandTableColumn(
                            Table.NestedJoin(
                                objectType, {"type_index"},
                                typeEav, {"type_index"},
                                "_te", JoinKind.Inner
                            ),
                            "_te",
                            {"path_index", "value_string", "value_double", "value_boolean"},
                            {"path_index", "value_string", "value_double", "value_boolean"}
                        ),
                        propCols
                    ),
                    {"object_index", "path_index"},
                    instanceProps, {"object_index", "path_index"},
                    "_dup", JoinKind.LeftAnti
                ),
                {"_dup"}
            )
        else
            #table(propCols, {}),

        allProps = Table.Combine({instanceProps, typeProps}),

        withPath = Table.ExpandTableColumn(
            Table.NestedJoin(
                allProps, {"path_index"},
                paths, {"path_index"},
                "_p", JoinKind.Inner
            ),
            "_p", {"path"}, {"path"}
        ),

        // exactly one of the value_* columns is set per row; consumer coalesces
        withValue = Table.AddColumn(
            withPath,
            "value",
            each
                if [value_string] <> null then [value_string]
                else if [value_double] <> null then [value_double]
                else [value_boolean]
        ),

        // paths that would collide with the fixed output columns get suffixed
        // (only matters for the wide mode's generated column names)
        reservedNames = {
            "Application ID", "Object Type", "Property", "Value", "Version ID",
            "Model Info", "Source Model", "object_index", "application_id", "value"
        },
        slim = Table.TransformColumns(
            Table.SelectColumns(withValue, {"object_index", "path", "value"}),
            {{"path", each if List.Contains(reservedNames, _) then _ & " (property)" else _, type text}}
        ),

        // (object, path) must be unique; buffer so the whole join pipeline is
        // evaluated exactly once
        deduped = Table.Buffer(Table.Distinct(slim, {"object_index", "path"})),

        // ---- tall output: one row per (object, property) --------------------
        tallTable =
            let
                joined = Table.ExpandTableColumn(
                    Table.NestedJoin(
                        base, {"object_index"},
                        deduped, {"object_index"},
                        "_props", JoinKind.LeftOuter
                    ),
                    "_props", {"path", "value"}, {"Property", "Value"}
                )
            in
                Table.TransformColumnTypes(
                    Table.RenameColumns(
                        Table.RemoveColumns(joined, {"object_index"}),
                        {{"application_id", "Application ID"}}
                    ),
                    {
                        {"Application ID", type text},
                        {"Object Type", type nullable text},
                        {"Property", type nullable text}
                    }
                ),

        // ---- wide output: one row per object, one column per path -----------
        result = if not expand then
            tallTable
        else
            let
                distinctPaths = List.Sort(List.Distinct(Table.Column(deduped, "path"))),

                // group to one record per object, weave the identity fields into
                // each record, and materialize via Table.FromRecords with an
                // explicit column list. Do NOT use Table.Pivot or
                // Table.ExpandRecordColumn here — both take minutes at real model
                // scale (thousands of objects x 1000+ paths); this runs in seconds.
                grouped = Table.Group(
                    deduped,
                    {"object_index"},
                    {{"__props", each Record.FromList([value], [path]), type record}}
                ),

                baseWithProps = Table.ExpandTableColumn(
                    Table.NestedJoin(
                        base, {"object_index"},
                        grouped, {"object_index"},
                        "_g", JoinKind.LeftOuter
                    ),
                    "_g", {"__props"}, {"__props"}
                ),

                fullRecords = Table.TransformRows(
                    baseWithProps,
                    (r) =>
                        Record.Combine({
                            [#"Application ID" = r[application_id], #"Object Type" = r[#"Object Type"]],
                            if r[__props] = null then [] else r[__props]
                        })
                ),

                wide = if List.IsEmpty(distinctPaths) then
                    Table.TransformColumnTypes(
                        Table.RenameColumns(
                            Table.RemoveColumns(base, {"object_index"}),
                            {{"application_id", "Application ID"}}
                        ),
                        {{"Application ID", type text}, {"Object Type", type nullable text}}
                    )
                else
                    Table.FromRecords(
                        fullRecords,
                        {"Application ID", "Object Type"} & distinctPaths,
                        MissingField.UseNull
                    )
            in
                wide
    in
        result
