// Builds the object/property table from a 4.0 artifact bundle's eav parquet files.
//
// Default (expand = false) — TALL: one row per (object, property):
//   "Application ID" | "Property" | "Value"
//   Property paths and values come from eav.eav plus type-level parameters
//   projected onto each object via object_type + type_eav (instance values win
//   on the same path — this is the type resolution; type names arrive as
//   ordinary property rows). Objects with zero properties keep a single row
//   with null Property/Value. This shape drives cross-filtering: slice by
//   Property/Value elsewhere -> the 3D visual receives the matching
//   Application IDs.
//
// expand = true — WIDE: one row per object, one column per property path.
//
// deps carries the shared module functions so this file doesn't re-load them:
//   deps[ReadBundleTable](files, suffix, required)
(deps as record, files as list, expand as logical) as table =>
    let
        ReadBundleTable = deps[ReadBundleTable],

        // ---- mandatory tables ----------------------------------------------
        objects = Table.Buffer(
            Table.SelectColumns(
                ReadBundleTable(files, ".eav.objects.parquet", true),
                {"object_index", "application_id"}
            )
        ),
        paths = Table.Buffer(ReadBundleTable(files, ".eav.paths.parquet", true)),
        eav = ReadBundleTable(files, ".eav.eav.parquet", true),

        // ---- optional type tables (graceful skip when absent) --------------
        objectTypeRaw = ReadBundleTable(files, ".eav.object_type.parquet", false),
        objectType = if objectTypeRaw = null then null else Table.Buffer(objectTypeRaw),
        typeEavRaw = ReadBundleTable(files, ".eav.type_eav.parquet", false),
        typeEav = if typeEavRaw = null then null else Table.Buffer(typeEavRaw),
        hasTypes = objectType <> null and typeEav <> null,

        // ---- tall property pipeline (both modes) ----------------------------
        propCols = {"object_index", "path_index", "value_string", "value_double", "value_boolean"},
        instanceProps = Table.Buffer(Table.SelectColumns(eav, propCols)),

        // type-level params projected per object; instance values win:
        // anti-join drops any (object, path) already present on the instance
        typeProps = if hasTypes then
            Table.RemoveColumns(
                Table.NestedJoin(
                    Table.SelectColumns(
                        Table.ExpandTableColumn(
                            Table.NestedJoin(
                                objectType, {"type_index"},
                                typeEav, {"type_index"},
                                "_te", JoinKind.Inner
                            ),
                            "_te",
                            {"path_index", "value_string", "value_double", "value_boolean"},
                            {"path_index", "value_string", "value_double", "value_boolean"}
                        ),
                        propCols
                    ),
                    {"object_index", "path_index"},
                    instanceProps, {"object_index", "path_index"},
                    "_dup", JoinKind.LeftAnti
                ),
                {"_dup"}
            )
        else
            #table(propCols, {}),

        allProps = Table.Combine({instanceProps, typeProps}),

        withPath = Table.ExpandTableColumn(
            Table.NestedJoin(
                allProps, {"path_index"},
                paths, {"path_index"},
                "_p", JoinKind.Inner
            ),
            "_p", {"path"}, {"path"}
        ),

        // exactly one of the value_* columns is set per row; consumer coalesces
        withValue = Table.AddColumn(
            withPath,
            "value",
            each
                if [value_string] <> null then [value_string]
                else if [value_double] <> null then [value_double]
                else [value_boolean]
        ),

        // paths that would collide with the fixed output columns get suffixed
        // (only matters for the wide mode's generated column names)
        reservedNames = {
            "Application ID", "Property", "Value", "Model Info", "Source Model",
            "object_index", "application_id", "value"
        },
        slim = Table.TransformColumns(
            Table.SelectColumns(withValue, {"object_index", "path", "value"}),
            {{"path", each if List.Contains(reservedNames, _) then _ & " (property)" else _, type text}}
        ),

        // (object, path) must be unique; buffer so the whole join pipeline is
        // evaluated exactly once
        deduped = Table.Buffer(Table.Distinct(slim, {"object_index", "path"})),

        // ---- tall output: one row per (object, property) --------------------
        tallTable =
            let
                joined = Table.ExpandTableColumn(
                    Table.NestedJoin(
                        objects, {"object_index"},
                        deduped, {"object_index"},
                        "_props", JoinKind.LeftOuter
                    ),
                    "_props", {"path", "value"}, {"Property", "Value"}
                )
            in
                Table.TransformColumnTypes(
                    Table.RenameColumns(
                        Table.RemoveColumns(joined, {"object_index"}),
                        {{"application_id", "Application ID"}}
                    ),
                    {
                        {"Application ID", type text},
                        {"Property", type nullable text}
                    }
                ),

        // ---- wide output: one row per object, one column per path -----------
        result = if not expand then
            tallTable
        else
            let
                distinctPaths = List.Sort(List.Distinct(Table.Column(deduped, "path"))),

                // group to one record per object, weave the identity field into
                // each record, and materialize via Table.FromRecords with an
                // explicit column list. Do NOT use Table.Pivot or
                // Table.ExpandRecordColumn here — both take minutes at real model
                // scale (thousands of objects x 1000+ paths); this runs in seconds.
                grouped = Table.Group(
                    deduped,
                    {"object_index"},
                    {{"__props", each Record.FromList([value], [path]), type record}}
                ),

                baseWithProps = Table.ExpandTableColumn(
                    Table.NestedJoin(
                        objects, {"object_index"},
                        grouped, {"object_index"},
                        "_g", JoinKind.LeftOuter
                    ),
                    "_g", {"__props"}, {"__props"}
                ),

                fullRecords = Table.TransformRows(
                    baseWithProps,
                    (r) =>
                        Record.Combine({
                            [#"Application ID" = r[application_id]],
                            if r[__props] = null then [] else r[__props]
                        })
                ),

                wide = if List.IsEmpty(distinctPaths) then
                    Table.TransformColumnTypes(
                        Table.RenameColumns(
                            Table.RemoveColumns(objects, {"object_index"}),
                            {{"application_id", "Application ID"}}
                        ),
                        {{"Application ID", type text}}
                    )
                else
                    Table.FromRecords(
                        fullRecords,
                        {"Application ID"} & distinctPaths,
                        MissingField.UseNull
                    )
            in
                wide
    in
        result
