// function for getting structured object data
(url as text) as table =>
    let
        GetModel = Extension.LoadFunction("GetModel.pqm"),
        FetchEavParquet = Extension.LoadFunction("FetchEavParquet.pqm"),

        Extension.LoadFunction = (fileName as text) =>
            let
                binary = Extension.Contents(fileName),
                asText = Text.FromBinary(binary)
            in
                try
                    Expression.Evaluate(asText, #shared)
                catch (e) =>
                    error
                        [
                            Reason = "Extension.LoadFunction Failure",
                            Message.Format = "Loading '#{0}' failed - '#{1}': '#{2}'",
                            Message.Parameters = {fileName, e[Reason], e[Message]},
                            Detail = [File = fileName, Error = e]
                        ],

        modelInfo = GetModel(url),
        rootId = modelInfo[rootObjectId],

        EavTable = FetchEavParquet(url),

        RequiredColumns = Table.SelectColumns(
            EavTable,
            {"object_id", "path", "value_text", "value_num", "type", "units", "internal_definition_name"},
            MissingField.UseNull
        ),

        NormalizeValue = (row as record) as any =>
            let
                rowType = Text.Lower(Text.From(Record.FieldOrDefault(row, "type", ""))),
                valueText = Record.FieldOrDefault(row, "value_text", null),
                valueNum = Record.FieldOrDefault(row, "value_num", null),
                normalized = if rowType = "number" and valueNum <> null then
                    valueNum
                else if rowType = "boolean" or rowType = "bool" then
                    if valueText = null then
                        null
                    else
                        Text.Lower(Text.From(valueText)) = "true"
                else if valueText <> null then
                    valueText
                else
                    valueNum
            in
                normalized,

        WithValues = Table.AddColumn(
            RequiredColumns,
            "Value",
            each NormalizeValue(_),
            type any
        ),

        RowsToRecord = (rows as table, optional pathPrefix as nullable text, optional stripPrefix as nullable logical) as record =>
            let
                prefix = if pathPrefix = null then null else pathPrefix,
                shouldStripPrefix = if stripPrefix = null then false else stripPrefix,
                filteredRows = if prefix = null then
                    rows
                else
                    Table.SelectRows(
                        rows,
                        each [path] <> null and Text.StartsWith(Text.From([path]), prefix)
                    ),
                withNames = Table.AddColumn(
                    filteredRows,
                    "Name",
                    each if [path] = null then
                        null
                    else if prefix <> null and shouldStripPrefix then
                        Text.Range(Text.From([path]), Text.Length(prefix))
                    else
                        Text.From([path]),
                    type text
                ),
                nonEmptyNames = Table.SelectRows(
                    withNames,
                    each [Name] <> null and [Name] <> ""
                ),
                firstValueByName = Table.Group(
                    nonEmptyNames,
                    {"Name"},
                    {{"Value", each List.First(List.RemoveNulls([Value]) & {null}), type any}}
                ),
                result = if Table.RowCount(firstValueByName) = 0 then
                    []
                else
                    Record.FromTable(firstValueByName)
            in
                result,

        GroupedByObject = Table.Group(
            WithValues,
            {"object_id"},
            {{"Rows", each _, type table}}
        ),

        FieldsToRemove = {"__closure", "totalChildrenCount", "renderMaterialProxies"},

        ObjectRecords = List.Transform(
            Table.ToRecords(GroupedByObject),
            each
                let
                    objectId = Record.FieldOrDefault(_, "object_id", null),
                    rows = Record.FieldOrDefault(_, "Rows", #table({}, {})),
                    dataRecord = RowsToRecord(rows, null, false),
                    cleanedRecord = Record.RemoveFields(dataRecord, FieldsToRemove, MissingField.Ignore),
                    propertiesRecord = RowsToRecord(rows, "properties.", true),
                    hasProperties = Record.FieldCount(propertiesRecord) > 0
                in
                    [
                        #"Object IDs" = objectId,
                        #"Speckle Type" = Record.FieldOrDefault(dataRecord, "speckle_type", null),
                        #"Version Object ID" = rootId,
                        #"Model Info" = rootId,
                        #"Application ID" = Record.FieldOrDefault(dataRecord, "applicationId", null),
                        data = cleanedRecord,
                        properties = if hasProperties then propertiesRecord else null
                    ]
        ),

        BasicTable = Table.FromRecords(
            ObjectRecords,
            type table [
                #"Object IDs" = nullable text,
                #"Speckle Type" = nullable text,
                #"Version Object ID" = nullable text,
                #"Model Info" = nullable text,
                #"Application ID" = nullable text,
                data = record,
                properties = nullable record
            ]
        ),

        SafeText = (value as any) as text =>
            if value = null then "" else Text.From(value),

        ShouldExcludeRow = (row as record) as logical =>
            let
                speckleType = SafeText(Record.FieldOrDefault(row, "Speckle Type", ""))
            in
                speckleType = "Speckle.Core.Models.DataChunk" or
                Text.Contains(speckleType, "Objects.Other.RawEncoding"),

        HasDataObjects = Table.RowCount(
            Table.SelectRows(
                BasicTable,
                each Text.Contains(SafeText(Record.FieldOrDefault(_, "Speckle Type", "")), "DataObject")
                     and not ShouldExcludeRow(_)
            )
        ) > 0,

        FilteredTable = if HasDataObjects then
            Table.SelectRows(
                BasicTable,
                each Text.Contains(SafeText(Record.FieldOrDefault(_, "Speckle Type", "")), "DataObject")
                     and not ShouldExcludeRow(_)
            )
        else
            Table.SelectRows(BasicTable, each not ShouldExcludeRow(_))
    in
        FilteredTable
