// Fast path for grouping EAV rows without creating a dedicated properties column.
(
    baseUrl as text,
    projectId as text,
    modelId as text,
    versionId as text,
    rootObjectId as text,
    token as text,
    optional includeMaterialQuantities as nullable logical
) as table =>
    let
        FetchEavParquet = Extension.LoadFunction("FetchEavParquet.pqm"),

        Extension.LoadFunction = (fileName as text) =>
            let
                binary = Extension.Contents(fileName),
                asText = Text.FromBinary(binary)
            in
                try
                    Expression.Evaluate(asText, #shared)
                catch (e) =>
                    error
                        [
                            Reason = "Extension.LoadFunction Failure",
                            Message.Format = "Loading '#{0}' failed - '#{1}': '#{2}'",
                            Message.Parameters = {fileName, e[Reason], e[Message]},
                            Detail = [File = fileName, Error = e]
                        ],

        EavTable = FetchEavParquet(
            baseUrl,
            projectId,
            modelId,
            versionId,
            token
        ),

        ShouldIncludeMaterialQuantities = if includeMaterialQuantities = null then false else includeMaterialQuantities,
        MaterialQuantitiesPath = "properties.Material Quantities",
        MaterialQuantitiesPrefix = MaterialQuantitiesPath & ".",

        RowsToRecord = (rows as table) as record =>
            Record.FromList(rows[value_text], rows[path]),

        IsMaterialQuantityPath = (path as any) as logical =>
            if not Value.Is(path, type text) or not Text.StartsWith(path, MaterialQuantitiesPrefix) then
                false
            else
                List.Count(Text.Split(Text.AfterDelimiter(path, MaterialQuantitiesPrefix), ".")) >= 2,

        MaterialRowsToRecord = (rows as table) as record =>
            let
                fieldNames = rows[fieldName],
                values = rows[value_text],
                fieldsRecord = List.Accumulate(
                    List.Positions(fieldNames),
                    [],
                    (current, index) =>
                        Record.AddField(
                            Record.RemoveFields(current, {fieldNames{index}}, MissingField.Ignore),
                            fieldNames{index},
                            values{index}
                        )
                )
            in
                Record.AddField(
                    Record.RemoveFields(fieldsRecord, {"materialName"}, MissingField.Ignore),
                    "materialName",
                    rows[materialName]{0}
                ),

        RowsToMaterialQuantities = (rows as table) as list =>
            let
                withSegments = Table.AddColumn(
                    rows,
                    "segments",
                    each Text.Split(Text.AfterDelimiter([path], MaterialQuantitiesPrefix), "."),
                    type list
                ),
                withMaterialName = Table.AddColumn(
                    withSegments,
                    "materialName",
                    each List.Last(List.FirstN([segments], List.Count([segments]) - 1)),
                    type text
                ),
                withFieldName = Table.AddColumn(
                    withMaterialName,
                    "fieldName",
                    each List.Last([segments]),
                    type text
                ),
                groupedByMaterial = Table.Group(
                    withFieldName,
                    {"materialName"},
                    {{"Material Quantity", MaterialRowsToRecord, type record}}
                )
            in
                groupedByMaterial[Material Quantity],

        RowsToGroupedObject = (rows as table) as record =>
            let
                rowsRecord = RowsToRecord(rows)
            in
                [
                    #"Speckle Type" = Record.FieldOrDefault(rowsRecord, "speckle_type", null),
                    #"Application ID" = Record.FieldOrDefault(rowsRecord, "applicationId", null),
                    Rows = rowsRecord
                ],

        GroupedByObjectId = Table.Group(
            EavTable,
            {"object_id"},
            {{"Grouped Object", RowsToGroupedObject, type record}},
            GroupKind.Local
        ),

        ExpandedGroupedByObjectId = Table.ExpandRecordColumn(
            GroupedByObjectId,
            "Grouped Object",
            {"Speckle Type", "Application ID", "Rows"},
            {"Speckle Type", "Application ID", "Rows"}
        ),

        DataObjects = Table.SelectRows(
            ExpandedGroupedByObjectId,
            each [#"Speckle Type"] <> null
                and Text.Contains(Text.From([#"Speckle Type"]), "DataObject")
        ),

        FinalGroupedByObjectId = if Table.IsEmpty(DataObjects) then
            ExpandedGroupedByObjectId
        else
            DataObjects,

        MaterialQuantityRows = if ShouldIncludeMaterialQuantities then
            Table.SelectRows(EavTable, each IsMaterialQuantityPath([path]))
        else
            #table({"object_id", "path", "value_text"}, {}),

        GroupedMaterialQuantities = if ShouldIncludeMaterialQuantities and not Table.IsEmpty(MaterialQuantityRows) then
            Table.Group(
                MaterialQuantityRows,
                {"object_id"},
                {{"materialQuantities", RowsToMaterialQuantities, type list}}
            )
        else
            null,

        WithMaterialQuantities = if ShouldIncludeMaterialQuantities and GroupedMaterialQuantities <> null then
            let
                nested = Table.NestedJoin(
                    FinalGroupedByObjectId,
                    {"object_id"},
                    GroupedMaterialQuantities,
                    {"object_id"},
                    "Material Quantities",
                    JoinKind.LeftOuter
                ),
                expanded = Table.ExpandTableColumn(
                    nested,
                    "Material Quantities",
                    {"materialQuantities"},
                    {"Material Quantities"}
                )
            in
                Table.ReplaceValue(
                    expanded,
                    null,
                    {},
                    Replacer.ReplaceValue,
                    {"Material Quantities"}
                )
        else if ShouldIncludeMaterialQuantities then
            Table.AddColumn(FinalGroupedByObjectId, "Material Quantities", each {}, type list)
        else
            FinalGroupedByObjectId,

        RenamedFinalTable = Table.RenameColumns(
            WithMaterialQuantities,
            {
                {"object_id", "Object IDs"},
                {"Rows", "data"}
            }
        )
    in
        RenamedFinalTable
