(url as text) as table =>
    let
        headers = [#"Content-Type" = "application/json"],
        postData = Json.FromValue([key = 235.7, value = 41.53]),
        response = Web.Contents(
            "http://localhost:8091/send-data",
            [
                Headers = headers,
                Content = postData
            ]
        ),
        jsonResponse = Json.Document(response)
    in
        jsonResponse