// Adds selected EAV values to the Objects table in the passed navigation
// source, or to an optional Objects override, split by source:
// values from the Property Values (instance) fact appear in an unprefixed
// column, and values from the Type Properties fact, projected per object
// through the Object Types bridge, appear in a Type_-prefixed column
// (Area / Type_Area). The five star-schema tables are unpacked from Source by
// key. An Objects override may be filtered or carry extra columns; its keys
// restrict both fact sides without buffering a fact-sized list. useFullPaths
// picks the column naming mode:
// false (default) uses the shortest unique trailing part of each dotted path,
// true the entire path. The Type_ prefix applies in both modes.
(
    source as table,
    propertyPaths as list,
    optional objects as nullable table,
    optional useFullPaths as nullable logical
) as table =>
    let
        // Only the columns the enrichment actually touches are required;
        // extra columns are tolerated everywhere (users pass transformed
        // tables, and extra Objects columns feed collision detection below).
        RequireColumns = (tbl as table, parameterName as text, requiredColumns as list) as table =>
            let
                missingColumns = List.Select(
                    requiredColumns,
                    each not Table.HasColumns(tbl, {_})
                )
            in
                if List.IsEmpty(missingColumns) then
                    tbl
                else
                    error Error.Record(
                        "Speckle.AddProperties.MissingColumns",
                        "The " & parameterName & " table is missing required columns: "
                            & Text.Combine(missingColumns, ", ") & ".",
                        [
                            Parameter = parameterName,
                            MissingColumns = missingColumns,
                            RequiredColumns = requiredColumns
                        ]
                    ),
        // A plain Objects table in the first position is the retired public
        // convention. Give it a direct migration error before checking the
        // navigation shape.
        validatedSourceColumns = if Table.HasColumns(source, {"Object Key"})
            and not Table.HasColumns(source, {"Key", "Data"}) then
            error Error.Record(
                "Speckle.AddProperties.SignatureChanged",
                "The signature changed: pass the Speckle.GetTables navigation table (Source) as the first argument. Expected: "
                    & "Speckle.AddProperties(source, propertyPaths, objects, useFullPaths).",
                [
                    ExpectedParameters = {
                        "source", "propertyPaths", "objects", "useFullPaths"
                    }
                ]
            )
        else
            RequireColumns(source, "source", {"Key", "Data"}),
        requiredSourceKeys = {
            "objects", "properties", "paths", "object-types", "type-properties"
        },
        sourceKeys = Table.Column(validatedSourceColumns, "Key"),
        missingSourceKeys = List.Select(
            requiredSourceKeys,
            each not List.Contains(sourceKeys, _, Comparer.Ordinal)
        ),
        validatedSource = if List.IsEmpty(missingSourceKeys) then
            validatedSourceColumns
        else
            error Error.Record(
                "Speckle.AddProperties.MissingSourceKeys",
                "The source navigation table is missing required keys: "
                    & Text.Combine(missingSourceKeys, ", ") & ".",
                [
                    MissingKeys = missingSourceKeys,
                    RequiredKeys = requiredSourceKeys
                ]
            ),
        sourceObjects = validatedSource{[Key = "objects"]}[Data],
        propertyValues = validatedSource{[Key = "properties"]}[Data],
        paths = validatedSource{[Key = "paths"]}[Data],
        objectTypes = validatedSource{[Key = "object-types"]}[Data],
        typeProperties = validatedSource{[Key = "type-properties"]}[Data],
        hasObjectsOverride = Value.Is(objects, type table),
        selectedObjects = if hasObjectsOverride then objects else sourceObjects,
        validatedObjects = RequireColumns(selectedObjects, "objects", {"Object Key"}),
        validatedPropertyValues = RequireColumns(
            propertyValues, "propertyValues", {"Object Key", "path_key", "Value"}
        ),
        validatedPathsTable = RequireColumns(paths, "paths", {"path_key", "Property"}),
        validatedObjectTypes = RequireColumns(objectTypes, "objectTypes", {"Object Key", "type_key"}),
        validatedTypeProperties = RequireColumns(
            typeProperties, "typeProperties", {"type_key", "path_key", "Value"}
        ),
        invalidPathIndexes = List.Select(
            List.Positions(propertyPaths),
            (i) =>
                let
                    value = propertyPaths{i}
                in
                    if Value.Is(value, type text) then Text.Trim(value) = "" else true
        ),
        validatedPaths = if List.IsEmpty(invalidPathIndexes) then
            propertyPaths
        else
            error Error.Record(
                "Speckle.AddProperties.InvalidPropertyPaths",
                "propertyPaths contains invalid items at positions "
                    & Text.Combine(List.Transform(invalidPathIndexes, each Text.From(_ + 1)), ", ")
                    & ". Each item must be non-empty text.",
                [Positions = List.Transform(invalidPathIndexes, each _ + 1)]
            ),
        wanted = List.Distinct(
            List.Transform(validatedPaths, each Text.Trim(_)),
            Comparer.Ordinal
        ),
        existingNames = Table.ColumnNames(validatedObjects),
        pathParts = List.Transform(wanted, each Text.Split(_, ".")),
        Candidate = (parts as list, depth as number) as text =>
            Text.Combine(List.LastN(parts, List.Min({depth, List.Count(parts)})), "."),

        // Orphan bridge rows are ignored. More than one bridge row for an
        // object that is present in Objects is invalid, even if the rows match.
        bridgeRows = Table.RemoveColumns(
            Table.NestedJoin(
                Table.SelectColumns(validatedObjectTypes, {"Object Key", "type_key"}),
                {"Object Key"},
                Table.SelectColumns(validatedObjects, {"Object Key"}), {"Object Key"},
                "__obj", JoinKind.Inner
            ),
            {"__obj"}
        ),
        duplicateObjectKeys = Table.Column(
            Table.SelectRows(
                Table.Group(bridgeRows, {"Object Key"}, {{"__count", Table.RowCount, Int64.Type}}),
                each [__count] > 1
            ),
            "Object Key"
        ),
        validatedBridge = if List.IsEmpty(duplicateObjectKeys) then
            bridgeRows
        else
            error Error.Record(
                "Speckle.AddProperties.InvalidObjectTypes",
                "Object Types must contain at most one row per object. Repeated Object Key values: "
                    & Text.Combine(List.Transform(duplicateObjectKeys, each Text.From(_)), ", ")
                    & ".",
                [ObjectKeys = duplicateObjectKeys]
            ),

        // Paths is the small dimension. Filter it before either fact join so
        // the large fact scans carry only requested keys and the raw Value.
        wantedPaths = Table.SelectColumns(
            Table.SelectRows(
                validatedPathsTable,
                each List.Contains(wanted, [Property], Comparer.Ordinal)
            ),
            {"path_key", "Property"}
        ),
        SelectRequestedPropertyValues = (facts as table, grainKey as text) as table =>
            Table.ExpandTableColumn(
                Table.NestedJoin(
                    Table.SelectColumns(facts, {grainKey, "path_key", "Value"}),
                    {"path_key"},
                    wantedPaths, {"path_key"},
                    "__wantedPath", JoinKind.Inner
                ),
                "__wantedPath", {"Property"}, {"__property"}
            ),
        requestedInstanceValues = SelectRequestedPropertyValues(
            validatedPropertyValues, "Object Key"
        ),
        // The full-model path stays unchanged. With an Objects override, a
        // streaming inner join drops unrelated instance facts before grouping.
        // Do not replace this with a buffered key list: both inputs may be
        // fact-sized.
        instanceValues = if hasObjectsOverride then
            Table.RemoveColumns(
                Table.NestedJoin(
                    requestedInstanceValues, {"Object Key"},
                    Table.SelectColumns(validatedObjects, {"Object Key"}), {"Object Key"},
                    "__obj", JoinKind.Inner
                ),
                {"__obj"}
            )
        else
            requestedInstanceValues,
        requestedTypeValues = SelectRequestedPropertyValues(validatedTypeProperties, "type_key"),
        projectedTypeValues = Table.ExpandTableColumn(
            Table.NestedJoin(
                validatedBridge, {"type_key"},
                requestedTypeValues, {"type_key"},
                "__type", JoinKind.Inner
            ),
            "__type", {"path_key", "Value", "__property"}, {"path_key", "Value", "__property"}
        ),

        // A path is type-backed iff any of its path_keys has at least one Type
        // Properties row: which fact table a row lives in is the authoritative
        // provenance signal (the path text carries none). The distinct lists
        // are wanted-sized, so buffering them is safe; never buffer the
        // fact-sized tables (see the SCALE note in GetEavModel.pqm).
        typeBackedProperties = List.Buffer(
            List.Distinct(Table.Column(requestedTypeValues, "__property"), Comparer.Ordinal)
        ),
        instanceBackedProperties = List.Buffer(
            List.Distinct(Table.Column(instanceValues, "__property"), Comparer.Ordinal)
        ),
        emitsTypeColumn = List.Transform(
            wanted,
            each List.Contains(typeBackedProperties, _, Comparer.Ordinal)
        ),
        // A non-type-backed path always emits its unprefixed column without
        // any instance existence check (a factless path stays a single all-null
        // column). A type-backed path emits the unprefixed column only when an
        // instance override row exists — an override coexists with the type row
        // under the same path, so the instance check cannot be skipped.
        emitsInstanceColumn = List.Transform(
            List.Positions(wanted),
            (i) =>
                not emitsTypeColumn{i}
                    or List.Contains(instanceBackedProperties, wanted{i}, Comparer.Ordinal)
        ),

        // Collision detection runs over the final emitted names. Both variants
        // of a path share its suffix depth; a conflict on either variant grows
        // that path.
        EmittedVariants = (base as text, i as number) as list =>
            (if emitsInstanceColumn{i} then {base} else {})
                & (if emitsTypeColumn{i} then {"Type_" & base} else {}),
        ResolveNames = (depths as list) as list =>
            let
                candidates = List.Transform(
                    List.Positions(wanted),
                    (i) => Candidate(pathParts{i}, depths{i})
                ),
                variants = List.Buffer(
                    List.Transform(
                        List.Positions(wanted),
                        (i) => EmittedVariants(candidates{i}, i)
                    )
                ),
                OwnersOf = (name as text) as list =>
                    List.Select(
                        List.Positions(variants),
                        (j) => List.Contains(variants{j}, name, Comparer.Ordinal)
                    ),
                existingConflicts = List.Transform(
                    variants,
                    (names) => List.AnyTrue(
                        List.Transform(
                            names,
                            (name) => List.Contains(existingNames, name, Comparer.Ordinal)
                        )
                    )
                ),
                duplicatedNames = List.Transform(
                    variants,
                    (names) => List.Select(names, (name) => List.Count(OwnersOf(name)) > 1)
                ),
                duplicateConflicts = List.Transform(duplicatedNames, each not List.IsEmpty(_)),
                conflicts = List.Transform(
                    List.Positions(wanted),
                    (i) => existingConflicts{i} or duplicateConflicts{i}
                ),
                canGrow = List.Transform(
                    List.Positions(depths),
                    (i) => depths{i} < List.Count(pathParts{i})
                ),
                growableConflicts = List.Transform(
                    List.Positions(conflicts),
                    (i) => conflicts{i} and canGrow{i}
                ),
                nextDepths = List.Transform(
                    List.Positions(depths),
                    (i) => if conflicts{i} and canGrow{i} then depths{i} + 1 else depths{i}
                ),
                // Residual clashes — growth exhausted on every conflicted
                // path — disambiguate with numeric suffixes claimed in request
                // order: the first claimant keeps the clean name, later ones
                // count up (.1, .2, …) past occupied names. Both variants of
                // a path suffix together so its Area/Type_Area pair stays
                // aligned.
                suffixedNames = List.Accumulate(
                    List.Positions(wanted),
                    [taken = existingNames, names = {}],
                    (state, i) =>
                        let
                            Claim = (suffix as number) as text =>
                                let
                                    attempt = if suffix = 0 then
                                        candidates{i}
                                    else
                                        candidates{i} & "." & Text.From(suffix),
                                    clashes = List.AnyTrue(
                                        List.Transform(
                                            EmittedVariants(attempt, i),
                                            (name) => List.Contains(state[taken], name, Comparer.Ordinal)
                                        )
                                    )
                                in
                                    if clashes then @Claim(suffix + 1) else attempt,
                            final = Claim(0)
                        in
                            [
                                taken = state[taken] & EmittedVariants(final, i),
                                names = state[names] & {final}
                            ]
                )[names]
            in
                if List.AnyTrue(growableConflicts) then
                    @ResolveNames(nextDepths)
                else if List.AnyTrue(conflicts) then
                    suffixedNames
                else
                    candidates,
        // useFullPaths = true seeds every depth at its maximum: names cannot
        // grow, so residual collisions (a literal Object Key path, a literal
        // Type_* path) go straight to the numeric-suffix pass instead of
        // renaming by depth
        outputNames = ResolveNames(
            if (useFullPaths ?? false) then
                List.Transform(pathParts, List.Count)
            else
                List.Transform(wanted, each 1)
        ),
        emittedNames = List.Combine(
            List.Transform(
                List.Positions(wanted),
                (i) => EmittedVariants(outputNames{i}, i)
            )
        ),

        // Rename __property to the final emitted column name per side before
        // combining. Cross-side field collisions are impossible by
        // construction (the prefix separates them), so record construction
        // below stays the loud-failure path for duplicate facts.
        instanceColumnNames = Record.FromList(outputNames, wanted),
        typeColumnNames = Record.FromList(
            List.Transform(outputNames, each "Type_" & _),
            wanted
        ),
        RenameToEmittedColumn = (values as table, columnNames as record) as table =>
            Table.TransformColumns(
                values,
                {{"__property", each Record.Field(columnNames, _), type text}}
            ),
        emittedValues = Table.SelectColumns(
            Table.Combine({
                RenameToEmittedColumn(instanceValues, instanceColumnNames),
                RenameToEmittedColumn(projectedTypeValues, typeColumnNames)
            }),
            {"Object Key", "Value", "__property"}
        ),
        propertyValuesByObject = Table.Group(
            emittedValues,
            {"Object Key"},
            // Duplicate (Object Key, path_key) facts on either side
            // intentionally reach record construction and fail rather than
            // being silently selected.
            {{"__props", each Record.FromList([Value], [__property]), type record}}
        ),
        withProperties = Table.ExpandTableColumn(
            Table.NestedJoin(
                validatedObjects, {"Object Key"},
                propertyValuesByObject, {"Object Key"},
                "__group", JoinKind.LeftOuter
            ),
            "__group", {"__props"}, {"__props"}
        )
    in
        if List.IsEmpty(wanted) then
            // an empty selection returns the exact Objects value, metadata
            // included, without touching the fact tables; source-shape and
            // Object Key validation still fire
            validatedObjects
        else
            Table.ExpandRecordColumn(withProperties, "__props", emittedNames, emittedNames)
