// Adds selected EAV values to the Objects navigation table, split by source:
// values from the Properties (instance) fact appear in an unprefixed column,
// and values from the Type Properties fact, projected per object through the
// Object Types bridge, appear in a Type_-prefixed column (Area / Type_Area).
(source as table, propertyPaths as list) as table =>
    let
        requiredKeys = {"objects", "properties", "object-types", "type-properties", "paths"},
        hasNavigationColumns = Table.HasColumns(source, {"Key", "Data"}),
        availableKeys = if hasNavigationColumns then
            List.Select(Table.Column(source, "Key"), each Value.Is(_, type text))
        else
            {},
        missingKeys = if hasNavigationColumns then
            List.Select(
                requiredKeys,
                each not List.Contains(availableKeys, _, Comparer.Ordinal)
            )
        else
            requiredKeys,
        validatedSource = if not hasNavigationColumns or not List.IsEmpty(missingKeys) then
            error Error.Record(
                "Speckle.AddProperties.InvalidNavigationSource",
                "The source is missing required Speckle navigation entries: "
                    & Text.Combine(missingKeys, ", ")
                    & ". Expected: Speckle.AddProperties(Speckle.GetTables(url), propertyPaths).",
                [MissingKeys = missingKeys, RequiredKeys = requiredKeys]
            )
        else
            source,
        objects = validatedSource{[Key = "objects"]}[Data],
        properties = validatedSource{[Key = "properties"]}[Data],
        objectTypes = validatedSource{[Key = "object-types"]}[Data],
        typeProperties = validatedSource{[Key = "type-properties"]}[Data],
        paths = validatedSource{[Key = "paths"]}[Data],
        invalidPathIndexes = List.Select(
            List.Positions(propertyPaths),
            (i) =>
                let
                    value = propertyPaths{i}
                in
                    if Value.Is(value, type text) then Text.Trim(value) = "" else true
        ),
        validatedPaths = if List.IsEmpty(invalidPathIndexes) then
            propertyPaths
        else
            error Error.Record(
                "Speckle.AddProperties.InvalidPropertyPaths",
                "propertyPaths contains invalid items at positions "
                    & Text.Combine(List.Transform(invalidPathIndexes, each Text.From(_ + 1)), ", ")
                    & ". Each item must be non-empty text.",
                [Positions = List.Transform(invalidPathIndexes, each _ + 1)]
            ),
        wanted = List.Distinct(
            List.Transform(validatedPaths, each Text.Trim(_)),
            Comparer.Ordinal
        ),
        existingNames = Table.ColumnNames(objects),
        pathParts = List.Transform(wanted, each Text.Split(_, ".")),
        Candidate = (parts as list, depth as number) as text =>
            Text.Combine(List.LastN(parts, List.Min({depth, List.Count(parts)})), "."),

        // Orphan bridge rows are ignored. More than one bridge row for an
        // object that is present in Objects is invalid, even if the rows match.
        bridgeRows = Table.RemoveColumns(
            Table.NestedJoin(
                Table.SelectColumns(objectTypes, {"object_key", "type_key"}),
                {"object_key"},
                Table.SelectColumns(objects, {"object_key"}), {"object_key"},
                "__obj", JoinKind.Inner
            ),
            {"__obj"}
        ),
        duplicateObjectKeys = Table.Column(
            Table.SelectRows(
                Table.Group(bridgeRows, {"object_key"}, {{"__count", Table.RowCount, Int64.Type}}),
                each [__count] > 1
            ),
            "object_key"
        ),
        validatedBridge = if List.IsEmpty(duplicateObjectKeys) then
            bridgeRows
        else
            error Error.Record(
                "Speckle.AddProperties.InvalidObjectTypes",
                "Object Types must contain at most one row per object. Repeated object_key values: "
                    & Text.Combine(List.Transform(duplicateObjectKeys, each Text.From(_)), ", ")
                    & ".",
                [ObjectKeys = duplicateObjectKeys]
            ),

        // Paths is the small dimension. Filter it before either fact join so
        // the large fact scans carry only requested keys and the raw Value.
        wantedPaths = Table.SelectColumns(
            Table.SelectRows(
                paths,
                each List.Contains(wanted, [Property], Comparer.Ordinal)
            ),
            {"path_key", "Property"}
        ),
        SelectRequestedPropertyValues = (facts as table, grainKey as text) as table =>
            Table.ExpandTableColumn(
                Table.NestedJoin(
                    Table.SelectColumns(facts, {grainKey, "path_key", "Value"}),
                    {"path_key"},
                    wantedPaths, {"path_key"},
                    "__wantedPath", JoinKind.Inner
                ),
                "__wantedPath", {"Property"}, {"__property"}
            ),
        instanceValues = SelectRequestedPropertyValues(properties, "object_key"),
        requestedTypeValues = SelectRequestedPropertyValues(typeProperties, "type_key"),
        projectedTypeValues = Table.ExpandTableColumn(
            Table.NestedJoin(
                validatedBridge, {"type_key"},
                requestedTypeValues, {"type_key"},
                "__type", JoinKind.Inner
            ),
            "__type", {"path_key", "Value", "__property"}, {"path_key", "Value", "__property"}
        ),

        // A path is type-backed iff any of its path_keys has at least one Type
        // Properties row: which fact table a row lives in is the authoritative
        // provenance signal (the path text carries none). The distinct lists
        // are wanted-sized, so buffering them is safe; never buffer the
        // fact-sized tables (see the SCALE note in GetEavModel.pqm).
        typeBackedProperties = List.Buffer(
            List.Distinct(Table.Column(requestedTypeValues, "__property"), Comparer.Ordinal)
        ),
        instanceBackedProperties = List.Buffer(
            List.Distinct(Table.Column(instanceValues, "__property"), Comparer.Ordinal)
        ),
        emitsTypeColumn = List.Transform(
            wanted,
            each List.Contains(typeBackedProperties, _, Comparer.Ordinal)
        ),
        // A non-type-backed path always emits its unprefixed column without
        // any instance existence check (a factless path stays a single all-null
        // column). A type-backed path emits the unprefixed column only when an
        // instance override row exists — an override coexists with the type row
        // under the same path, so the instance check cannot be skipped.
        emitsInstanceColumn = List.Transform(
            List.Positions(wanted),
            (i) =>
                not emitsTypeColumn{i}
                    or List.Contains(instanceBackedProperties, wanted{i}, Comparer.Ordinal)
        ),

        // Collision detection runs over the final emitted names. Both variants
        // of a path share its suffix depth; a conflict on either variant grows
        // that path.
        EmittedVariants = (base as text, i as number) as list =>
            (if emitsInstanceColumn{i} then {base} else {})
                & (if emitsTypeColumn{i} then {"Type_" & base} else {}),
        ResolveNames = (depths as list) as list =>
            let
                candidates = List.Transform(
                    List.Positions(wanted),
                    (i) => Candidate(pathParts{i}, depths{i})
                ),
                variants = List.Buffer(
                    List.Transform(
                        List.Positions(wanted),
                        (i) => EmittedVariants(candidates{i}, i)
                    )
                ),
                OwnersOf = (name as text) as list =>
                    List.Select(
                        List.Positions(variants),
                        (j) => List.Contains(variants{j}, name, Comparer.Ordinal)
                    ),
                existingConflicts = List.Transform(
                    variants,
                    (names) => List.AnyTrue(
                        List.Transform(
                            names,
                            (name) => List.Contains(existingNames, name, Comparer.Ordinal)
                        )
                    )
                ),
                duplicatedNames = List.Transform(
                    variants,
                    (names) => List.Select(names, (name) => List.Count(OwnersOf(name)) > 1)
                ),
                duplicateConflicts = List.Transform(duplicatedNames, each not List.IsEmpty(_)),
                conflicts = List.Transform(
                    List.Positions(wanted),
                    (i) => existingConflicts{i} or duplicateConflicts{i}
                ),
                canGrow = List.Transform(
                    List.Positions(depths),
                    (i) => depths{i} < List.Count(pathParts{i})
                ),
                unresolvableConflicts = List.Transform(
                    List.Positions(conflicts),
                    (i) =>
                        (existingConflicts{i} and not canGrow{i})
                        or List.AnyTrue(
                            List.Transform(
                                duplicatedNames{i},
                                (name) => not List.AnyTrue(
                                    List.Transform(OwnersOf(name), (j) => canGrow{j})
                                )
                            )
                        )
                ),
                nextDepths = List.Transform(
                    List.Positions(depths),
                    (i) => if conflicts{i} and canGrow{i} then depths{i} + 1 else depths{i}
                )
            in
                if List.AnyTrue(unresolvableConflicts) then
                    error Error.Record(
                        "Speckle.AddProperties.NameCollision",
                        "Requested property columns cannot be made unique against the Objects columns.",
                        [PropertyPaths = wanted, ExistingColumns = existingNames]
                    )
                else if List.AnyTrue(conflicts) then
                    @ResolveNames(nextDepths)
                else
                    candidates,
        outputNames = ResolveNames(List.Transform(wanted, each 1)),
        emittedNames = List.Combine(
            List.Transform(
                List.Positions(wanted),
                (i) => EmittedVariants(outputNames{i}, i)
            )
        ),

        // Rename __property to the final emitted column name per side before
        // combining. Cross-side field collisions are impossible by
        // construction (the prefix separates them), so record construction
        // below stays the loud-failure path for duplicate facts.
        instanceColumnNames = Record.FromList(outputNames, wanted),
        typeColumnNames = Record.FromList(
            List.Transform(outputNames, each "Type_" & _),
            wanted
        ),
        RenameToEmittedColumn = (values as table, columnNames as record) as table =>
            Table.TransformColumns(
                values,
                {{"__property", each Record.Field(columnNames, _), type text}}
            ),
        emittedValues = Table.SelectColumns(
            Table.Combine({
                RenameToEmittedColumn(instanceValues, instanceColumnNames),
                RenameToEmittedColumn(projectedTypeValues, typeColumnNames)
            }),
            {"object_key", "Value", "__property"}
        ),
        propertyValuesByObject = Table.Group(
            emittedValues,
            {"object_key"},
            // Duplicate (object_key, path_key) facts on either side
            // intentionally reach record construction and fail rather than
            // being silently selected.
            {{"__props", each Record.FromList([Value], [__property]), type record}}
        ),
        withProperties = Table.ExpandTableColumn(
            Table.NestedJoin(
                objects, {"object_key"},
                propertyValuesByObject, {"object_key"},
                "__group", JoinKind.LeftOuter
            ),
            "__group", {"__props"}, {"__props"}
        )
    in
        if List.IsEmpty(wanted) then
            objects
        else
            Table.ExpandRecordColumn(withProperties, "__props", emittedNames, emittedNames)
