// Composes the public Speckle.GetTables navigation table (ENG-9165) from the
// five already-combined star-schema tables. With the default Simplified
// layout the Navigator shows two entries — Objects and the model-bound
// Properties function — while the four hidden supporting rows stay
// addressable by key for Speckle.AddProperties and Speckle.AddAllProperties.
// The All tables layout unhides the supporting rows for users building their
// own relationships.
//
// deps:        [NavigationTable = ..., AddProperties = ...]
// tables:      [Objects = ..., Properties = ..., Paths = ..., ObjectTypes = ...,
//               TypeProperties = ...]
// tableLayout: null | "Simplified" | "All tables" (case-insensitive)
(deps as record, tables as record, optional tableLayout as nullable text) as table =>
    let
        NavigationTable = deps[NavigationTable],
        AddProperties = deps[AddProperties],

        // Table layout — the Speckle.GetTables advanced option. Named after
        // the public export so the structured error reads correctly there.
        allowedTableLayouts = {"Simplified", "All tables"},
        showAllTables = if tableLayout = null
            or Comparer.OrdinalIgnoreCase(tableLayout, "Simplified") = 0 then
            false
        else if Comparer.OrdinalIgnoreCase(tableLayout, "All tables") = 0 then
            true
        else
            error Error.Record(
                "Speckle.GetTables.InvalidTableLayout",
                "TableLayout must be one of: "
                    & Text.Combine(allowedTableLayouts, ", ")
                    & ". Got: " & tableLayout & ".",
                [TableLayout = tableLayout, AllowedValues = allowedTableLayouts]
            ),

        // the five keyed rows AddProperties indexes; hidden flags implement
        // the Navigator contract (Simplified shows only Objects as a table,
        // All tables shows every row). Keys are the stable API — the
        // Property Values row keeps its historical "properties" key.
        helperRows = {
            [name = "Objects", key = "objects", data = tables[Objects], itemKind = "Table", isLeaf = true],
            [name = "Property Values", key = "properties", data = tables[Properties], itemKind = "Table", isLeaf = true, hidden = not showAllTables],
            [name = "Property Paths", key = "paths", data = tables[Paths], itemKind = "Table", isLeaf = true, hidden = not showAllTables],
            [name = "Object Types", key = "object-types", data = tables[ObjectTypes], itemKind = "Table", isLeaf = true, hidden = not showAllTables],
            [name = "Type Properties", key = "type-properties", data = tables[TypeProperties], itemKind = "Table", isLeaf = true, hidden = not showAllTables]
        },

        // ExpandProperties closes over this private five-row navigator, not
        // over the public table it is itself a row of — building the helper
        // source first keeps the public navigation table non-recursive.
        // Its objects row carries only Object Key, so the bound function
        // returns a lean, relationship-ready table (Object Key + selected
        // property columns) instead of an enriched copy of Objects, and
        // collision detection sees only Object Key among the base columns.
        // The public helperRows keep the full Objects table for
        // Speckle.AddProperties and Speckle.AddAllProperties.
        helperSource = NavigationTable(
            List.Transform(
                helperRows,
                each if [key] = "objects" then
                    _ & [data = Table.SelectColumns([data], {"Object Key"})]
                else
                    _
            )
        ),

        // the selector catalogue: Property Paths values deduplicated in
        // first-appearance order. Federated models repeat identical path text
        // under per-source keys; the selector lists each path once and a
        // selection applies across all sources.
        propertyOptions = List.Buffer(
            List.Distinct(Table.Column(tables[Paths], "Property"), Comparer.Ordinal)
        ),

        ExpandProperties.Impl = (
            optional Properties as nullable list,
            optional ColumnNames as nullable text
        ) as table =>
            let
                selected = Properties ?? {},
                hasInvalidSelection = List.AnyTrue(
                    List.Transform(
                        selected,
                        each if Value.Is(_, type text) then Text.Trim(_) = "" else true
                    )
                ),
                orderedSelection = if hasInvalidSelection then
                    // hand the raw list through so AddProperties raises its
                    // structured invalid-path error with the caller's
                    // original one-based positions
                    selected
                else if List.IsEmpty(selected) then
                    {}
                else
                    let
                        normalized = List.Distinct(
                            List.Transform(selected, each Text.Trim(_)),
                            Comparer.Ordinal
                        ),
                        selectedLookup = Record.FromList(
                            List.Repeat({true}, List.Count(normalized)),
                            normalized
                        ),
                        availableLookup = Record.FromList(
                            List.Repeat({true}, List.Count(propertyOptions)),
                            propertyOptions
                        ),
                        // known selections follow the catalogue order shown in
                        // the selector, not caller order; paths missing from
                        // this model version trail behind them and surface
                        // downstream as all-null columns
                        known = List.Select(
                            propertyOptions,
                            each Record.HasFields(selectedLookup, _)
                        ),
                        disappeared = List.Select(
                            normalized,
                            each not Record.HasFields(availableLookup, _)
                        )
                    in
                        known & disappeared
            in
                // ColumnNames passes through unvalidated: AddProperties owns
                // the canonical validation and its structured error
                AddProperties(helperSource, orderedSelection, ColumnNames),

        ExpandProperties.Type = Type.ForFunction(
            [
                ReturnType = type table,
                Parameters = [
                    // no "(optional)" in captions: the Power BI parameter
                    // dialog appends that suffix itself for optional params
                    Properties = type nullable list meta [
                        Documentation.FieldCaption = "Properties",
                        Documentation.FieldDescription = "Dotted property paths (see the Property Paths table) to return as columns alongside Object Key. Instance values land in unprefixed columns and type values in Type_-prefixed columns. Selecting all properties can significantly increase refresh time and table width.",
                        Documentation.AllowedValues = propertyOptions
                    ],
                    ColumnNames = type nullable text meta [
                        Documentation.FieldCaption = "Column names",
                        Documentation.FieldDescription = "Default: Shortest. Shortest names each column with the shortest unique trailing part of its dotted path, growing only on collisions; Full path uses the entire dotted path. Type values keep the Type_ prefix in both modes.",
                        Documentation.AllowedValues = {"Shortest", "Full path"}
                    ]
                ]
            ],
            0
        ) meta [
            Documentation.Name = "Properties",
            Documentation.LongDescription = "Returns a lean table of Object Key plus the selected property columns, with one row per Objects row — relate it one-to-one to the Objects table on Object Key. An omitted, null or empty selection returns an Object Key-only table containing every object. Column names default to the shortest unique trailing part of each dotted path; set Column names to Full path to use entire paths. Selecting all properties can significantly increase refresh time and table width."
        ],
        ExpandProperties.Value = Value.ReplaceType(ExpandProperties.Impl, ExpandProperties.Type)
    in
        NavigationTable(
            helperRows
                & {
                    [
                        name = "Properties",
                        key = "expand-properties",
                        data = ExpandProperties.Value,
                        itemKind = "Function",
                        isLeaf = true
                    ]
                }
        )
