(url as text) as table =>
    let
        // single source of truth for the connector version (keep Speckle.pq [Version]
        // and Speckle.proj <Version> aligned with this)
        ConnectorVersion = "4.0.0",

        // the logic for importing functions from other files — this is the single
        // copy; leaf modules receive what they need via the deps record
        Extension.LoadFunction = (fileName as text) =>
            let
                binary = Extension.Contents(fileName),
                asText = Text.FromBinary(binary)
            in
                try
                    Expression.Evaluate(asText, #shared)
                catch (e) =>
                    error
                        [
                            Reason = "Extension.LoadFunction Failure",
                            Message.Format = "Loading '#{0}' failed - '#{1}': '#{2}'",
                            Message.Parameters = {fileName, e[Reason], e[Message]},
                            Detail = [File = fileName, Error = e]
                        ],

        Parser = Extension.LoadFunction("Parser.pqm"),
        CheckPermissions = Extension.LoadFunction("CheckPermissions.pqm"),
        GetUser = Extension.LoadFunction("GetUser.pqm"),
        GetWorkspace = Extension.LoadFunction("GetWorkspace.pqm"),
        ExchangeToken = Extension.LoadFunction("ExchangeToken.pqm"),
        GetModel = Extension.LoadFunction("GetModel.pqm"),
        FetchArtifacts = Extension.LoadFunction("FetchArtifacts.pqm"),
        ReadBundleTable = Extension.LoadFunction("ReadBundleTable.pqm"),
        GetEavModel = Extension.LoadFunction("GetEavModel.pqm"),
        NavigationTable = Extension.LoadFunction("NavigationTable.pqm"),
        GetStructuredData = Extension.LoadFunction("GetStructuredData.pqm"),
        ExpandRecord = Extension.LoadFunction("Utils.ExpandRecord.pqm"),
        EncodeUserInfo = Extension.LoadFunction("EncodeUserInfo.pqm"),
        MarkReceived = Extension.LoadFunction("MarkReceived.pqm"),
        ProjectModels = Extension.LoadFunction("Project.Models.pqm"),

        deps = [ReadBundleTable = ReadBundleTable],

        // federated models namespace their dense-int keys as ordinal * 2^32 + index
        KeySpace = 4294967296,

        // M is lazy: a side-effecting call only executes if its result is observed.
        // Observe(sideEffect, value) evaluates sideEffect and returns value.
        Observe = (sideEffect as any, value as any) as any =>
            if sideEffect = null then value else value,

        ProjectWideModelLimit = 10000,

        // parse the URL to determine load shape
        parsedUrl = Parser(url),

        expandedResourceIdString = if parsedUrl[isProjectWideModelLoad] then
            Text.Combine(ProjectModels(parsedUrl[baseUrl], parsedUrl[projectId], ProjectWideModelLimit), ",")
        else
            parsedUrl[resourceIdString],

        effectiveUrl = if parsedUrl[isProjectWideModelLoad] then
            Text.Combine({
                parsedUrl[baseUrl],
                "/projects/",
                parsedUrl[projectId],
                "/models/",
                expandedResourceIdString
            })
        else
            url,

        effectiveParsedUrl = Parser(effectiveUrl),

        metadataUrl = if parsedUrl[isProjectWideModelLoad] then url else effectiveUrl,

        // single permission guard
        permissionCheck = CheckPermissions(metadataUrl),
        permissionGuard = if not Record.HasFields(permissionCheck, {"authorized", "code", "message"}) then
            error "Invalid permission check result"
        else if not permissionCheck[authorized] then
            error Text.Format(
                "Permission denied: #{0} (Error code: #{1})",
                {permissionCheck[message], permissionCheck[code]}
            )
        else
            null,

        // user / workspace context + the single token exchange
        userInfo = GetUser(metadataUrl),
        powerfulToken = userInfo[Token],
        userEmail = userInfo[UserEmail],
        workspaceInfo = GetWorkspace(metadataUrl),

        tokenExchangeResult = ExchangeToken(
            powerfulToken,
            {"profile:read", "streams:read", "users:read"},
            effectiveParsedUrl[projectId],
            effectiveParsedUrl[baseUrl],
            effectiveParsedUrl[resourceIdString]
        ),

        // hard-fail if token exchange failed - do NOT use powerful token as fallback
        weakToken = if tokenExchangeResult[Success] then
            tokenExchangeResult[Token]
        else
            error [
                Reason = "TokenExchangeFailed",
                Message.Format = "Failed to exchange token for limited scope token: #{0}",
                Message.Parameters = {tokenExchangeResult[ErrorMessage]},
                Detail = [
                    ErrorMessage = tokenExchangeResult[ErrorMessage],
                    ProjectId = effectiveParsedUrl[projectId],
                    ServerUrl = effectiveParsedUrl[baseUrl]
                ]
            ],

        // empty star-schema shapes contributed by legacy (pre-4.0) models — their
        // properties come pre-flattened; the fact/paths entries are artifact-only
        EmptyProperties = #table(
            type table [
                object_key = Int64.Type,
                path_key = Int64.Type,
                #"Value Text" = nullable text,
                #"Value Number" = nullable number,
                #"Value Bool" = nullable logical,
                Value = any
            ],
            {}
        ),
        EmptyPaths = #table(type table [path_key = Int64.Type, Property = text], {}),

        // maps the legacy JSON-path table onto the 4.0 shapes:
        // "Application ID" := applicationId ?? speckle id; properties expanded to
        // columns, served on demand through ExpandProperties
        LegacyShapes = (t as table) as record =>
            let
                withAppId = Table.AddColumn(
                    t,
                    "__appId",
                    each if [Application ID] <> null then [Application ID] else [Object IDs],
                    type text
                ),
                expanded = if Table.HasColumns(withAppId, {"properties"}) then
                    try ExpandRecord(withAppId, "properties") otherwise withAppId
                else
                    withAppId,
                wide = Table.RenameColumns(
                    Table.RemoveColumns(
                        expanded,
                        {"Application ID", "Object IDs", "Version Object ID", "Model Info", "data", "properties"},
                        MissingField.Ignore
                    ),
                    {{"__appId", "Application ID"}},
                    MissingField.Ignore
                ),
                objectsOnly = Table.AddColumn(
                    Table.Distinct(Table.SelectColumns(wide, {"Application ID"})),
                    "object_key",
                    each null,
                    Int64.Type
                )
            in
                [
                    Objects = Table.SelectColumns(objectsOnly, {"object_key", "Application ID"}),
                    Properties = EmptyProperties,
                    Paths = EmptyPaths,
                    ObjectTypes = #table(type table [object_key = Int64.Type, type_key = Int64.Type], {}),
                    TypeProperties = Table.SelectColumns(
                        Table.AddColumn(EmptyProperties, "type_key", each null, Int64.Type),
                        {"type_key", "path_key", "Value Text", "Value Number", "Value Bool", "Value"}
                    ),
                    // legacy models have no path dictionary — expand straight off the
                    // JSON-expanded wide shape, missing paths arriving as nulls
                    ExpandProperties = (pathsText as text) as table =>
                        let
                            wanted = List.Distinct(
                                List.Select(
                                    List.Transform(Text.Split(pathsText, ","), each Text.Trim(_)),
                                    each _ <> ""
                                )
                            ),
                            selected = Table.SelectColumns(
                                wide,
                                {"Application ID"} & wanted,
                                MissingField.UseNull
                            )
                        in
                            Table.ReorderColumns(
                                Table.AddColumn(selected, "object_key", each null, Int64.Type),
                                {"object_key", "Application ID"} & wanted
                            )
                ],

        // loads one model and returns its star-schema shapes + per-model metadata
        ProcessSingleModel = (baseUrl as text, projectId as text, modelId as text, versionId as nullable text, ordinal as number) as record =>
            let
                singleModelUrl = Text.Combine({
                    baseUrl,
                    "/projects/",
                    projectId,
                    "/models/",
                    modelId,
                    if versionId <> null then Text.Combine({"@", versionId}) else ""
                }),

                modelInfo = GetModel(singleModelUrl),
                resolvedVersionId = if versionId <> null then versionId else modelInfo[versionId],

                // null -> the version predates 4.0 artifact bundles (legacy fallback)
                files = FetchArtifacts(baseUrl, projectId, modelInfo[modelId], resolvedVersionId, weakToken),
                isArtifact = files <> null,

                model = if isArtifact then
                    GetEavModel(deps, files, ordinal * KeySpace)
                else
                    LegacyShapes(GetStructuredData(singleModelUrl, weakToken)),

                // best-effort receipt tracking (forced via Observe below)
                markReceivedResult = try MarkReceived(powerfulToken, resolvedVersionId, projectId, baseUrl) otherwise false,

                userInfoBase = [
                    schemaVersion = 2,
                    pipeline = if isArtifact then "artifact" else "legacy",
                    server = baseUrl,
                    projectId = projectId,
                    modelId = modelInfo[modelId],
                    versionId = resolvedVersionId,
                    token = weakToken,
                    workspaceId = workspaceInfo[workspaceId],
                    workspaceName = workspaceInfo[workspaceName],
                    // workspaceLogo deliberately NOT in the blob: logos are base64
                    // data-URIs (tens of KB) and the blob repeats on EVERY data row —
                    // the visual fetches the logo itself via GraphQL using workspaceId
                    canHideBranding = workspaceInfo[canHideBranding],
                    sourceApplication = modelInfo[sourceApplication],
                    version = ConnectorVersion,
                    email = userEmail
                ],
                // the legacy visual path still needs the root object hash
                userInfoData = if isArtifact then
                    userInfoBase
                else
                    Record.AddField(userInfoBase, "rootObjectId", modelInfo[rootObjectId]),

                encodedUserInfo = Observe(markReceivedResult, EncodeUserInfo(userInfoData))
            in
                [
                    Model = model,
                    VersionId = resolvedVersionId,
                    // pinned federated entries stay distinguishable per version
                    SourceLabel = if versionId <> null then
                        Text.Combine({modelInfo[modelName], "-", versionId})
                    else
                        modelInfo[modelName],
                    EncodedUserInfo = encodedUserInfo
                ],

        // appends the shared per-load column (versionIds travel inside the blob)
        WithModelInfo = (t as table, modelInfoBlob as text) as table =>
            Table.AddColumn(t, "Model Info", each modelInfoBlob, type text),

        // combines per-model tables and assembles the navigation table.
        // Recommended PBI relationships: Objects 1-* Properties *-1 Property Paths
        // on object_key / path_key.
        BuildNavigation = (modelsData as list, addSourceModel as logical) as table =>
            let
                // delimiter chosen to avoid conflicts with base64 characters
                combinedBlobs = Text.Combine(List.Transform(modelsData, each [EncodedUserInfo]), "|||"),

                CombinePart = (getPart as function, withSource as logical) as table =>
                    Table.Combine(
                        List.Transform(
                            modelsData,
                            (m) =>
                                let
                                    t = getPart(m[Model])
                                in
                                    if withSource and addSourceModel then
                                        Table.AddColumn(t, "Source Model", (row) => m[SourceLabel], type text)
                                    else
                                        t
                        )
                    ),

                objectsT = WithModelInfo(CombinePart((mm) => mm[Objects], true), combinedBlobs),
                propertiesT = CombinePart((mm) => mm[Properties], false),
                pathsT = CombinePart((mm) => mm[Paths], false),
                objectTypesT = CombinePart((mm) => mm[ObjectTypes], false),
                typePropertiesT = CombinePart((mm) => mm[TypeProperties], false),

                // "Expand Properties" — the on-demand replacement for the old eager
                // Flat (Wide): the user invokes it with comma-separated property
                // paths (browse them in Property Paths) and only those columns are
                // evaluated. Lean output: object_key + the requested columns (no
                // Model Info blob, no Application ID — the 1:1 object_key
                // relationship to Objects carries identity). Federation: each model
                // expands independently, results union with namespaced object_keys;
                // paths absent in a model = null.
                expandPropertiesRaw = (propertyPaths as text) as table =>
                    Table.Combine(
                        List.Transform(
                            modelsData,
                            (m) =>
                                let
                                    t = m[Model][ExpandProperties](propertyPaths)
                                in
                                    if addSourceModel then
                                        Table.AddColumn(t, "Source Model", (row) => m[SourceLabel], type text)
                                    else
                                        t
                        )
                    ),
                expandPropertiesFn = Value.ReplaceType(
                    expandPropertiesRaw,
                    type function (
                        propertyPaths as (
                            type text meta [
                                Documentation.FieldCaption = "Property paths (comma-separated)",
                                Documentation.FieldDescription = "Dotted property paths as listed in the Property Paths table",
                                Documentation.SampleValues = {"category, properties.Dimensions.Area"}
                            ]
                        )
                    ) as table meta [
                        Documentation.Name = "Expand Properties",
                        Documentation.LongDescription =
                            "Returns object_key plus one column per requested property path (instance value wins over type value). "
                            & "Browse available paths in the Property Paths table. Only the requested paths are evaluated, so this "
                            & "stays fast on large models — relate the result to Objects 1:1 on object_key to slice the 3D visual."
                    ]
                )
            in
                NavigationTable({
                    [name = "Objects", key = "objects", data = objectsT, itemKind = "Table", isLeaf = true],
                    [name = "Properties", key = "properties", data = propertiesT, itemKind = "Table", isLeaf = true],
                    [name = "Property Paths", key = "paths", data = pathsT, itemKind = "Table", isLeaf = true],
                    [name = "Object Types", key = "object-types", data = objectTypesT, itemKind = "Table", isLeaf = true],
                    [name = "Type Properties", key = "type-properties", data = typePropertiesT, itemKind = "Table", isLeaf = true],
                    [name = "Expand Properties", key = "expand-properties", data = expandPropertiesFn, itemKind = "Function", isLeaf = true]
                }),

        results = Observe(
            permissionGuard,
            if effectiveParsedUrl[isFederated] = true then
                let
                    feds = effectiveParsedUrl[federatedModels],
                    modelsData = List.Transform(
                        List.Positions(feds),
                        (i) => ProcessSingleModel(
                            effectiveParsedUrl[baseUrl],
                            effectiveParsedUrl[projectId],
                            feds{i}[modelId],
                            feds{i}[versionId],
                            i
                        )
                    )
                in
                    BuildNavigation(modelsData, true)
            else
                BuildNavigation(
                    {
                        ProcessSingleModel(
                            effectiveParsedUrl[baseUrl],
                            effectiveParsedUrl[projectId],
                            effectiveParsedUrl[modelId],
                            effectiveParsedUrl[versionId],
                            0
                        )
                    },
                    false
                )
        )
    in
        results
