(url as text, optional ExpandProperties as logical) as table =>
    let
        shouldExpandProperties = if ExpandProperties = null then false else ExpandProperties,

        // single source of truth for the connector version (keep Speckle.pq [Version]
        // and Speckle.proj <Version> aligned with this)
        ConnectorVersion = "4.0.0",

        // the logic for importing functions from other files — this is the single
        // copy; leaf modules receive what they need via the deps record
        Extension.LoadFunction = (fileName as text) =>
            let
                binary = Extension.Contents(fileName),
                asText = Text.FromBinary(binary)
            in
                try
                    Expression.Evaluate(asText, #shared)
                catch (e) =>
                    error
                        [
                            Reason = "Extension.LoadFunction Failure",
                            Message.Format = "Loading '#{0}' failed - '#{1}': '#{2}'",
                            Message.Parameters = {fileName, e[Reason], e[Message]},
                            Detail = [File = fileName, Error = e]
                        ],

        Parser = Extension.LoadFunction("Parser.pqm"),
        CheckPermissions = Extension.LoadFunction("CheckPermissions.pqm"),
        GetUser = Extension.LoadFunction("GetUser.pqm"),
        GetWorkspace = Extension.LoadFunction("GetWorkspace.pqm"),
        ExchangeToken = Extension.LoadFunction("ExchangeToken.pqm"),
        GetModel = Extension.LoadFunction("GetModel.pqm"),
        FetchArtifacts = Extension.LoadFunction("FetchArtifacts.pqm"),
        ReadBundleTable = Extension.LoadFunction("ReadBundleTable.pqm"),
        GetEavWideTable = Extension.LoadFunction("GetEavWideTable.pqm"),
        GetStructuredData = Extension.LoadFunction("GetStructuredData.pqm"),
        ExpandRecord = Extension.LoadFunction("Utils.ExpandRecord.pqm"),
        EncodeUserInfo = Extension.LoadFunction("EncodeUserInfo.pqm"),
        MarkReceived = Extension.LoadFunction("MarkReceived.pqm"),
        ProjectModels = Extension.LoadFunction("Project.Models.pqm"),

        deps = [ReadBundleTable = ReadBundleTable],

        // M is lazy: a side-effecting call only executes if its result is observed.
        // Observe(sideEffect, value) evaluates sideEffect and returns value.
        Observe = (sideEffect as any, value as any) as any =>
            if sideEffect = null then value else value,

        ProjectWideModelLimit = 10000,

        // parse the URL to determine load shape
        parsedUrl = Parser(url),

        expandedResourceIdString = if parsedUrl[isProjectWideModelLoad] then
            Text.Combine(ProjectModels(parsedUrl[baseUrl], parsedUrl[projectId], ProjectWideModelLimit), ",")
        else
            parsedUrl[resourceIdString],

        effectiveUrl = if parsedUrl[isProjectWideModelLoad] then
            Text.Combine({
                parsedUrl[baseUrl],
                "/projects/",
                parsedUrl[projectId],
                "/models/",
                expandedResourceIdString
            })
        else
            url,

        effectiveParsedUrl = Parser(effectiveUrl),

        metadataUrl = if parsedUrl[isProjectWideModelLoad] then url else effectiveUrl,

        // single permission guard
        permissionCheck = CheckPermissions(metadataUrl),
        permissionGuard = if not Record.HasFields(permissionCheck, {"authorized", "code", "message"}) then
            error "Invalid permission check result"
        else if not permissionCheck[authorized] then
            error Text.Format(
                "Permission denied: #{0} (Error code: #{1})",
                {permissionCheck[message], permissionCheck[code]}
            )
        else
            null,

        // user / workspace context + the single token exchange
        userInfo = GetUser(metadataUrl),
        powerfulToken = userInfo[Token],
        userEmail = userInfo[UserEmail],
        workspaceInfo = GetWorkspace(metadataUrl),

        tokenExchangeResult = ExchangeToken(
            powerfulToken,
            {"profile:read", "streams:read", "users:read"},
            effectiveParsedUrl[projectId],
            effectiveParsedUrl[baseUrl],
            effectiveParsedUrl[resourceIdString]
        ),

        // hard-fail if token exchange failed - do NOT use powerful token as fallback
        weakToken = if tokenExchangeResult[Success] then
            tokenExchangeResult[Token]
        else
            error [
                Reason = "TokenExchangeFailed",
                Message.Format = "Failed to exchange token for limited scope token: #{0}",
                Message.Parameters = {tokenExchangeResult[ErrorMessage]},
                Detail = [
                    ErrorMessage = tokenExchangeResult[ErrorMessage],
                    ProjectId = effectiveParsedUrl[projectId],
                    ServerUrl = effectiveParsedUrl[baseUrl]
                ]
            ],

        // maps the legacy JSON-path table onto the 4.0 column contract:
        // "Application ID" := applicationId ?? speckle id, "Object Type" := Speckle Type
        LegacyToContract = (t as table) as table =>
            let
                withAppId = Table.AddColumn(
                    t,
                    "__appId",
                    each if [Application ID] <> null then [Application ID] else [Object IDs],
                    type text
                ),
                expanded = if shouldExpandProperties and Table.HasColumns(withAppId, {"properties"}) then
                    try ExpandRecord(withAppId, "properties") otherwise withAppId
                else
                    withAppId,
                cleaned = Table.RemoveColumns(
                    expanded,
                    {"Application ID", "Object IDs", "Version Object ID", "Model Info", "data", "properties"},
                    MissingField.Ignore
                ),
                renamed = Table.RenameColumns(
                    cleaned,
                    {{"__appId", "Application ID"}, {"Speckle Type", "Object Type"}},
                    MissingField.Ignore
                )
            in
                renamed,

        // loads one model and returns its table + the per-model metadata
        ProcessSingleModel = (baseUrl as text, projectId as text, modelId as text, versionId as nullable text) as record =>
            let
                singleModelUrl = Text.Combine({
                    baseUrl,
                    "/projects/",
                    projectId,
                    "/models/",
                    modelId,
                    if versionId <> null then Text.Combine({"@", versionId}) else ""
                }),

                modelInfo = GetModel(singleModelUrl),
                resolvedVersionId = if versionId <> null then versionId else modelInfo[versionId],

                // null -> the version predates 4.0 artifact bundles (legacy fallback)
                files = FetchArtifacts(baseUrl, projectId, modelInfo[modelId], resolvedVersionId, weakToken),
                isArtifact = files <> null,

                data = if isArtifact then
                    GetEavWideTable(deps, files, shouldExpandProperties)
                else
                    LegacyToContract(GetStructuredData(singleModelUrl, weakToken)),

                // best-effort receipt tracking (forced via Observe below)
                markReceivedResult = try MarkReceived(powerfulToken, resolvedVersionId, projectId, baseUrl) otherwise false,

                userInfoBase = [
                    schemaVersion = 2,
                    pipeline = if isArtifact then "artifact" else "legacy",
                    server = baseUrl,
                    projectId = projectId,
                    modelId = modelInfo[modelId],
                    versionId = resolvedVersionId,
                    token = weakToken,
                    workspaceId = workspaceInfo[workspaceId],
                    workspaceName = workspaceInfo[workspaceName],
                    workspaceLogo = workspaceInfo[workspaceLogo],
                    canHideBranding = workspaceInfo[canHideBranding],
                    sourceApplication = modelInfo[sourceApplication],
                    version = ConnectorVersion,
                    email = userEmail
                ],
                // the legacy visual path still needs the root object hash
                userInfoData = if isArtifact then
                    userInfoBase
                else
                    Record.AddField(userInfoBase, "rootObjectId", modelInfo[rootObjectId]),

                encodedUserInfo = Observe(markReceivedResult, EncodeUserInfo(userInfoData))
            in
                [
                    Data = data,
                    VersionId = resolvedVersionId,
                    // pinned federated entries stay distinguishable per version
                    SourceLabel = if versionId <> null then
                        Text.Combine({modelInfo[modelName], "-", versionId})
                    else
                        modelInfo[modelName],
                    EncodedUserInfo = encodedUserInfo
                ],

        // appends the shared per-load columns
        WithLoadColumns = (t as table, versionIds as text, modelInfoBlob as text) as table =>
            Table.AddColumn(
                Table.AddColumn(t, "Version ID", each versionIds, type text),
                "Model Info",
                each modelInfoBlob,
                type text
            ),

        results = Observe(
            permissionGuard,
            if effectiveParsedUrl[isFederated] = true then
                let
                    modelsData = List.Transform(
                        effectiveParsedUrl[federatedModels],
                        each ProcessSingleModel(
                            effectiveParsedUrl[baseUrl],
                            effectiveParsedUrl[projectId],
                            [modelId],
                            [versionId]
                        )
                    ),

                    allTables = List.Transform(
                        modelsData,
                        (m) => Table.AddColumn(m[Data], "Source Model", (row) => m[SourceLabel], type text)
                    ),

                    combinedVersionIds = Text.Combine(List.Transform(modelsData, each [VersionId]), ","),

                    // delimiter chosen to avoid conflicts with base64 characters
                    combinedBlobs = Text.Combine(List.Transform(modelsData, each [EncodedUserInfo]), "|||"),

                    // Table.Combine unions differing property columns (nulls elsewhere)
                    combinedData = Table.Combine(allTables)
                in
                    WithLoadColumns(combinedData, combinedVersionIds, combinedBlobs)
            else
                let
                    single = ProcessSingleModel(
                        effectiveParsedUrl[baseUrl],
                        effectiveParsedUrl[projectId],
                        effectiveParsedUrl[modelId],
                        effectiveParsedUrl[versionId]
                    )
                in
                    WithLoadColumns(single[Data], single[VersionId], single[EncodedUserInfo])
        )
    in
        results
